# Identificatorii proiectului în SonarQube
sonar.projectKey=CodeScan
sonar.projectName=app
sonar.projectVersion=1.0

# Unde se află codul sursă Python (ex: folderul app sau rădăcina .)
sonar.sources=./app
sonar.python.coverage.reportPaths=coverage.xml
# Specificarea limbajului
sonar.language=py
sonar.sourceEncoding=UTF-8

# (Opțional) Excluderea mediilor virtuale sau a folderelor de teste/build
sonar.exclusions=**/venv/**, **/__pycache__/**, **/*.pyc