name: CI-CD workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  Build_and_Push:
    runs-on: ubuntu-latest
    needs: Code_Scan  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest
      - name: Send notification to Slack
        uses: act10ns/slack@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: starting
          channel: '#all-github-notifications'
          message: Docker image built and pushed successfully!
        if: always()

  Code_Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Scan code
        uses: SonarSource/sonarqube-scan-action@v8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
      - name: Send notification to Slack
        uses: act10ns/slack@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: starting
          channel: '#all-github-notifications'
          message: Code scan passed!
        if: success()


  Deploy:
    runs-on: ubuntu-latest
    needs: Build_and_Push
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.0.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup SSH Connection
        uses: bondz/ssh-ec2-action@v2
        with:
          ec2-instance-id: i-096f4fa57a5575ec1
          remote-user: ubuntu
      - name: Deploy Docker Container
        run: |
            sudo docker pull ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            sudo docker run -d --name myapp -p 5000:5000 ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest

